getsentry/devenv

devenv/checks/failing_check_with_no_fix.py, doctor.py, tests/doctor/devenv/checks/failing_check_with_no_fix.py, tests/doctor/devenv/checks/passing_check_with_no_fix.py, tests/doctor/test_load_checks.py, tests/doctor/test_run_checks.py
Not every check will have an associated fix. This change makes fixers optional and adds logic to handle (auto-skip) checks without fixes.
=> Making having a fix optional

.github/workflows/build.yml, .github/workflows/lint.yml, .pre-commit-config.yaml, devenv/bootstrap.py, devenv/lib/fs.py, devenv/lib/proc.py, devenv/main.py, devenv/sync.py, pyproject.toml
Making devenv compatible with python 3.8 will allow us to use it in Sentry (which still relies on python 3.8).
=> Making devenv python 3.8 compatible

devenv/bootstrap.py, devenv/constants.py
This allows external contributors to bypass our GitHub authentication checks.
=> Adding env var for external contributors

.github/workflows/bootstrap.yml, ci/devenv-bootstrap.sh, devenv/bootstrap.py, devenv/lib/direnv.py, install-devenv.sh
i've grown weary of the 30+ minute macos-13 bootstrap runs and propose to only run them on main
a lot of it is the overhead with installing colima, and while colima is available on macos-12 runners it is not on 13: https://github.com/actions/runner-images/blob/macOS-12/20230825.1/images/macos/macos-13-Readme.md
in its stead i'm adding ubuntu-2204 runs for pull requests (which only takes 5 minutes lmao), which is also good because we want to support devenv on ubuntu
=> ci: regularly test on ubuntu 2204, move macos-13 to main only

devenv/lib/volta.py, devenv/main.py, tests/volta/test_install.py
we don't actually need this!
though i think we should have a `devenv exec` feature if user wants to access things like `node` through interactive shell - will followup with something like that
=> ref: modifying shellrc for volta is not necessary as it's self-contained

devenv/lib/volta.py, tests/volta/test_install.py
volta shims aren't on the PATH following https://github.com/getsentry/devenv/pull/51, easiest way to make them available while keeping user's shellrc modifications to a minimum is to put them in devenv's bin which should already be on PATH following an install-devenv.sh
=> fix: symlink volta bins into devenv bin

.github/workflows/bootstrap.yml, devenv/bootstrap.py, devenv/constants.py, devenv/lib/archive.py, devenv/lib/brew.py, devenv/lib/colima.py, devenv/lib/limactl.py, devenv/sync.py, tests/brew/test_install.py
some people have been running into issues with bad colima versions, with 0.6.2 being the known good one 
i haven't found a way to add/reference a local formula file to Brewfile, and i'm thinking the best path forward is to just let devenv install colima which is just a go binary which just works per my testing
really don't like how brew doesn't let you easily install a particular version of something and i don't want people to get broken by updating colima
=> feat: manage colima ourselves

tests/conftest.py, tests/lib/test_direnv.py
tests/lib/test_direnv.py currently passes locally if run by itself but not when other tests are run because previous imports are cached and they won't see the os.environ change
it works in ci because SHELL is already bash
so - we set this up in conftest since that's used to setup pytest before any tests are run
=> fix: set SHELL in conftest

tests/lib/test_volta.py, tests/test_bootstrap.py, tests/test_sync.py
this finishes replacing assert_has_calls (which can be true on subsets of calls) to strictly comparing against all calls done in-order
=> ref: replace assert_has_calls with comparing against ordered mock_calls

devenv/__main__.py
this makes it easier to rerun ourselves in a subprocess reliably (independent of PATH)
=> allow invoking devenv as `python -m devenv`

.github/workflows/bootstrap.yml, devenv/bootstrap.py, devenv/constants.py, devenv/lib/archive.py, devenv/lib/colima.py, devenv/lib/fs.py, devenv/lib/gcloud.py, devenv/lib/limactl.py, devenv/lib/proc.py, devenv/lib/venv.py, devenv/lib/volta.py, tests/lib/test_direnv.py, tests/lib/test_volta.py
This factors out bin_root, and moves bins like volta and colima into repolocal. This is pretty important as it'll avoid collisions with more than one repo. Honestly should have done this from the very beginning 😰 
since direnv will be used to put this on path and it's pretty stable, it remains in the global bin dir
volta covered by integration
colima/lima covered by integration in gha macos
gcloud and sync.sync are used by ops, no integration coverage yet
=> feat: repo local bins

install-devenv.sh
we shouldn't be installing the global devenv from `main` which is not very stable in between releases... pin it to 1.4.0 for now so new hires and anyone else running install-devenv.sh don't get stuck on some potentially bad commit
=> ref: pin global devenv to 1.4.0

devenv/pythons.py, tests/test_pythons.py
just noticed an unfortunate regression in 3b27f121788bcdbb1a4528061a588fc78da7bd63 where i misinlined pythons_root to {home}/pythons and not {root}/pythons, lol
could have easily been avoided with a simple unittest which i've added
=> fix: regression in pythons root

devenv/lib/colima.py, devenv/lib/gcloud.py, devenv/lib/tenv.py, devenv/lib/volta.py, tests/lib/test_volta.py
Instead of writing symlinks, we need shims that set VOLTA_HOME, forcing these repo-local bins to use the repo-local volta home for full containment. Otherwise, the default is to use ~/.volta.
This should be the last piece for full containment of repo-local bins (with the exception of ~/.lima which i'm willing to let slide).
=> ref: fully contain VOLTA_HOME

devenv/bootstrap.py
as of https://github.com/getsentry/sentry/pull/68379 and https://github.com/getsentry/getsentry/pull/13568, `make bootstrap` is no longer needed
=> ref: sentry bootstrap no longer needed

README.md, ci/devenv-bootstrap.sh, devenv/bootstrap.py, devenv/fetch.py, devenv/main.py
This pr separates bootstrapping the devenv tool from fetching workspace repositories. This has also added the ability to fetch any arbitrary github repo.
=> feat: Split bootstrap and fetch commands; add support for fetching any repo

devenv/fetch.py
this may speed up initial clone, but it makes working with the repository history terribly inefficient and breaks basic git operations
=> remove blobless clones

devenv/pythons.py, tests/conftest.py, tests/test_pythons.py
Devenv could be useful to setup the venv in CI, though at least in GHA `actions/setup-python` is much faster than a manual download of the matching python version. In CI, we usually take greater care for selecting the right python version already, so devenv could use that when it matches the expected version.
Downside of the current approach is that it silently falls back to downloading a new version if the system provided one doesn't match, which can regress CI times. That should be pretty visible in PRs, though.
=> Use system python for venv on CI

devenv/constants.py, devenv/lib/gcloud.py, devenv/lib/venv.py, devenv/main.py, tests/lib/test_venv.py
it's the small things in life...
Wanted to get these things in before I cut a new release for https://github.com/getsentry/sentry/pull/72870.
- adds `version/--version`, and `devenv` by itself now prints full usage (instead of pretty much nothing)
- fixes a little bug with gke-gcloud-auth-plugin not on devenv's path
- devenv venvs gitignore themselves!
=> devenv: small things

.github/workflows/bootstrap.yml, ci/devenv-bootstrap.sh, devenv/colima.py, devenv/lib/colima.py, devenv/lib/docker.py, devenv/main.py
Sentry will use this like this: https://github.com/getsentry/sentry/pull/74975
This improves on sentry's `scripts/start-colima.py` and makes starting colima more robust in that we check for host.docker.internal communication to actually work.
Also this lets people manage colima more easily now that it's exposed as cli and can be used in scripting too.
Currently there's a known issue where if you have a fresh colima vm, it doesn't work the first time and needs to be restarted - this affects new engineers, and those who had to `colima delete`. This issue becomes evident once you try and ingest events in devserver since relay relies on host.docker.internal.
=> feat: colima robust start and convenience commands

.envrc, .github/workflows/bootstrap.yml, .gitignore, ci/devenv-bootstrap.sh, ci/devenv-post-bootstrap.sh
After bootstrap+fetch we tell people to open a new terminal, so anything after `devenv fetch sentry` should be in a login shell.
This also replaces sentry's devenv config so we don't break when sentry's upgraded to python3.12.
I also wasn't able to figure out why `direnv allow` was exiting and doing nothing in CI, so just replacing with what it essentially needs to do for now.
=> ci: devenv-post-bootstrap.sh

README.md, ci/devenv-bootstrap.sh, devenv/lib/proc.py, devenv/main.py, devenv/update.py, tests/lib/test_proc.py
This adds a `devenv update` command for updating the global devenv install which people have been requesting. Most users outside of sentry are using global devenv (also, not all repos will need a python venv so no repo-local devenv) and we should better support this use case by making updates easy.
Up until now I've been recommending downloading and rerunning `install-devenv.sh`, but I just realized this is better: `~/.local/share/sentry-devenv/venv/bin/pip install -U sentry-devenv`
=> feat: devenv update

ci/devenv-bootstrap.sh, devenv/lib/node.py
@evanpurkhiser was having trouble with devenv sync bc he had configured a different npm prefix, this ensures we explicitly use our own for `install -g`'s
```
› .devenv/bin/npm install -g yarn@1.22.22
changed 1 package in 596ms
sentry macbook-work py › devenv sync
installing yarn 1.22.22...
changed 1 package in 408ms
failed to install yarn 1.22.22!
```
=> fix(node): ignore npm prefix if configured, ensuring we use our own

devenv/bootstrap.py, devenv/lib/github.py
bootstrap on a new machine will have this non-error printed which is confusing - silence it the first time because ssh keys aren't provisioned yet
```
Command `sh -c 'ssh -T git@github.com 2>&1'` failed! (code 255)
combined out:
git@github.com: Permission denied (publickey).
Are you a Sentry employee? (Y/n): 
```
=> ref: silence first time ssh access check error during bootstrap

devenv/lib/archive.py, tests/lib/test_archive.py
redo of https://github.com/getsentry/devenv/pull/152 but I give up on trying to make sure a common prefix is stripped
gnu tar's behavior is just to unconditionally strip components so we'll just follow suit
i also rewrote the existing tests to actually have valid python tarfiles and also assert for file tree equality to be absolutely thorough
=> feat: strip_n and ability to download blobs from homebrew (take 2)

.github/workflows/bootstrap.yml, devenv/lib/colima.py
this adds a shim for colima that:
1. <s>if start, reexecs as `devenv colima start` - some people in the past have run `colima delete` then `colima start` to try and reset state, however `colima start` has bad defaults and (currently) suffers from double-start problem which `devenv colima start` solves</s>
2. proactively ensures that COLIMA_HOME is ~/.colima. The version I'm trying to upgrade us to prioritizes using XDG_CONFIG_HOME (https://github.com/abiosoft/colima/commit/05fd57766899b5b9c3eed14e8889083a546e3353) if set.
=> ref: colima shim

devenv/lib/gcloud.py, devenv/lib/node.py, devenv/lib/tenv.py
f/u to https://github.com/getsentry/devenv/pull/154/commits/8ee991f624ba08115214ed6f793ccb7a3b7cfd83 for the remaining shims
additionally, quotes are now needed around `${{PATH}}` so it becomes `"${PATH}"` after str.format
=> fix: unquote shell escaped parts of shims but keep $PATH quoted

README.md, devenv/lib/repository.py, devenv/sync.py, tests/lib/test_repository.py
sync now checks for an optionally defined minimum devenv version and recommends how to update the global devenv accordingly in order to use it to run sync to completion
=> feat: require minimum devenv version for a repo

devenv/lib/venv.py, tests/lib/test_venv.py
closes https://github.com/getsentry/devenv/issues/155
also removes an outdated example (repo readme is better and more visible)
=> fix: venv.ensure checks for python existence

devenv/update.py
There's been some general confusion around this, so let's just unconditionally update global devenv and if local, suggest that the now updated global devenv be used to run sync.
=> ref: unconditionally update global devenv

devenv/lib/archive.py, tests/lib/test_archive.py
discovered in https://github.com/getsentry/devenv/pull/170
fails on limactl linux x86-64 homebrew archive because `lima/0.23.2` needs to be stripped away
```
tarinfo = <TarInfo 'share/lima/templates/almalinux.yaml' at 0x7fdba9372e00>
def _find_link_target(self, tarinfo):
"""Find the target member of a symlink or hardlink member in the
archive.
"""
if tarinfo.issym():
linkname = "/".join(filter(None, (os.path.dirname(tarinfo.name), tarinfo.linkname)))
limit = None
else:
linkname = tarinfo.linkname
limit = tarinfo
member = self._getmember(linkname, tarinfo=limit, normalize=True)
if member is None:
>           raise KeyError("linkname %r not found" % linkname)
E           KeyError: "linkname 'lima/0.23.2/share/lima/templates/almalinux-9.yaml' not found"
```
=> fix: also strip hardlink target

README.md, ci/devenv-bootstrap.sh, devenv/checks/credsStore.py, devenv/doctor.py
This implements the credsStore fix in doctor as a "builtin" command since it's not repo-specific.
I hope to add some more "builtin" checks and fixes soon since I want to recommend people try `devenv doctor` before proceeding with more specific troubleshooting. One idea is the detection of docker desktop running and killing it.
https://getsentry.atlassian.net/issues/DEVINFRA-475
=> feat: credsStore fix in doctor

.envrc, devenv/bootstrap.py, devenv/update.py
Previously we tried to unconditionally update the global devenv but some people do not have it globally installed.
If local devenv update is run, it recommends running `devenv sync` but still updates the global tools.
=> ref: only update global devenv if it exists

devenv/lib/gcloud.py
This script is necessary for interacting with container/artifact registry via docker.
=> Makes the docker-credential-gcloud script available.

devenv/lib/gcloud.py
This will make devenv trigger a reinstall if the file isn't there.
=> Makes the gcloud install check for docker-credential-gcloud existing.

ci/devenv-bootstrap.sh
since the python 3.13 upgrade the bootstrap job has been failing:
```
failed command (code 2):
make apply-migrations
Output:
/home/runner/code/sentry/scripts/lib.sh: line 67: red: unbound variable
make: *** [Makefile:23: apply-migrations] Error 1
```
this is because in sentry:
```
$ CI=1 make apply-migrations                                                                                        2
/Users/josh/dev/sentry/scripts/lib.sh: line 67: red: unbound variable
make: *** [apply-migrations] Error 1
```
updating our devenv config will avoid this as we pass the ifs in sentry's `query-valid-python-version` 
will f/u with a real fix in sentry (@asottile-sentry should we just remove the `query-valid-python-version` piece altogether?)
=> fix(ci): unbound variable error during bootstrap

README.md
This PR updates the install instructions:
- point out that the installation file must be called `install-devenv.sh` as it apparently calls itself while running
- add a curl command to the installation commands for ease of use
(I ran into this pitfall while going through the installation instructions, so I thought we might as well keep future users from making the same mistakes)
=> doc: Update install instructions

README.md, devenv/lib/docker.py
The global docker install doesn't come with buildx. We should install it - some local development expects buildx to be available. I was building gocd images and they use buildx.
=> feat: install docker-buildx

devenv/checks/limaDns.py, devenv/colima.py, devenv/lib/colima.py
this adds a 2-stage fix for dns problems (first restarting systemd-resolved, then restarting colima itself)
and using external dns should long term fix this issue 
<s>i don't think this kind of problem is reportable or fixable upstream as the default with colima is just to use the host's dns resolution (which can break in any number of ways depending on what kind of network you connect to) - i could suggest for them to use a better default though?</s>
> i haven't been able to reproduce that^ but actually host dns works, its just the resolver is broken
```
josh@CTKP7QRX4L.local ~  $ colima exec sudo systemctl stop systemd-resolved.service                               0
josh@CTKP7QRX4L.local ~  $ ~/dev/devenv/.tox/py311/bin/devenv doctor                                              0 …
```
=> feat(doctor): two stage fix for dns problems, and use external DNS servers

devenv/lib/archive.py, tests/lib/test_archive.py
https://linear.app/getsentry/issue/DI-748/devenv-docker-buildx-bugged-installs-due-to-docker-desktop-overwriting
=> fix: remove archive.download dest before downloading if it's a symlink

devenv/main.py, pyproject.toml
The behavior stays the same. The deprecated `enable_tracing=True` sets `traces_sample_rate=1.0` internally.
See https://docs.sentry.io/platforms/python/migration/2.x-to-3.x#configuration
=> chore: Make `devenv` forward compatible with Sentry SDK 3.0.0

README.md, ci/devenv-bootstrap.sh, ci/integration/repo/devenv/config.ini, install-devenv.sh, tests/lib/test_venv.py
Appears https://github.com/indygreg/python-build-standalone redirecs now to https://github.com/astral-sh/python-build-standalone
Adjusted everything that matched.
There are still some other string matches, did not change these:
```
$ git grep indygreg
install-devenv.sh:# translate from uname output to indygreg release tags:
install-devenv.sh:indygreg_os() {
install-devenv.sh:indygreg_cpu() {
install-devenv.sh:  indygreg_platform="$(indygreg_cpu)-$(indygreg_os)"
install-devenv.sh:  case "$indygreg_platform" in
install-devenv.sh:      error "Unexpected platform; please ask in #discuss-dev-infra or contact <team-devenv@sentry.io>: ($platform -> $indygreg_platform)"
install-devenv.sh:  tarball="cpython-$version+$release-$indygreg_platform-install_only.tar.gz"
```
=> Adjust for indygreg/python-build-standalone -> astral-sh redirect

README.md, devenv/update.py
i'm stupid
no one has really run into this because we have an alternate message in sentry devenv sync.py:
```
Hi! To reduce potential breakage we've defined a minimum
devenv version ({minimum_version}) to run sync.
Please run the following to update your global devenv:
devenv update
Then, use it to run sync this one time.
{constants.root}/bin/devenv sync
```
=> fix: update x.x.x

devenv/update.py
in the rare event that ~/.local/share/sentry-devenv/bin/devenv (originally installed by install-devenv.sh) is removed, `devenv update` should restore it
=> fix: ensure global devenv symlink exists if removed
