.github/workflows/test.yml
bootstrap.py
constants.py
install-devenv.sh
main.py

skeleton for bootstrap, including interactively configuring coderoot.
Will be following up with individual portions of bootstrap after; trying to break this up into smaller reviewable PRs.

feat: bootstrap skeleton

---

doctor.py

The goal of this PR is to break logic (especially duplicate logic) into their own functions, making the code more readable in the process. Additionally, I worked to improve the typing to add more safety. One thing I plan to add soon is the ability to not include a fix since not all checks will have fixes.

Cleaning up the doctor

---

doctor.py
tests/doctor/devenv/checks/broken_check.py
tests/doctor/test_load_checks.py
tests/doctor/test_run_checks.py

Adding logic to handle checks are broken and have exceptions thrown in them.

Handle broken checks

---

doctor.py
tests/doctor/devenv/checks/broken_fix.py
tests/doctor/test_attempt_fix.py
tests/doctor/test_load_checks.py

Adding logic to handle fixes that are broken and have exceptions thrown in them.

Handle broken fixes

---

doctor.py

Adding a bit of documentation around what each function does as well as some documentation to the Check class.

Adding doc strings to functions

---

doctor.py
tests/doctor/devenv/checks/bad_check.py
tests/doctor/devenv/checks/bad_fix.py
tests/doctor/test_load_checks.py

As an added layer of protection against incorrect checks, I added additional type checking. Additionally, I added some messages to the assertions to provide better feedback about why a check is invalid.

Adding better type checking when loading checks

---

.github/workflows/test.yml
bootstrap.py
constants.py
install-devenv.sh
lib/brew.py
lib/github.py

these fixes were implemented after testing on my intel mac from scratch
also for some reason, macos-13 seems to have changed a bit (and broke in the process), so i've fixed CI as well (mostly by nuking away more homebrew state preinstalled on the runner image)
getsentry doesn't succeed yet - i'll f/u with this soon

feat: support intel macs

---

bootstrap.py
constants.py
lib/brew.py
lib/proc.py
lib/volta.py
sync.py

f/u to https://github.com/getsentry/devenv/pull/19#discussion_r1362664193
> we should factor out shells entirely -- this won't work on weird shells (and -i / etc. opens us up to people's broken rcfiles)

ref: factor out use of interactive shell so we're not as affected by user's environment

---

devenv/main.py

missed this spot that buck removede

fix: enforce coderoot

---

.github/workflows/bootstrap.yml
Makefile
ci/devenv-bootstrap.sh

see https://github.com/getsentry/sentry/pull/60030

fix(ci): bootstrap should not fail-thru

---

devenv/main.py
pyproject.toml

https://sentry.sentry.io/issues/4681805346/?project=5723503&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

feat: add sentry-sdk

---

tests/lib/test_archive.py
tox.ini

originally from my zstd branch -- but that's not needed anymore

ref: add test for archive unpack

---

devenv/lib/proc.py

this moves our managed paths first and then prepends that to user's PATH for more flexibility with people with more customized environments

feat: prepend to PATH

---

.github/workflows/bootstrap.yml
devenv/bootstrap.py
devenv/sync.py

supersedes https://github.com/getsentry/devenv/pull/84

test: pin colima to 0.6.2 for macos-13

---

devenv/bootstrap.py

resolves #53
reproduced locally with:
```
$ rm -rf getsentry
$ PATH=$PWD/sentry/.venv/bin:$PATH ./sentry/.venv/bin/devenv bootstrap
...
--> Building platform assets
--> Finished bootstrapping. Have a nice day.
rm -rf /Users/asottile/workspace/getsentry/getsentry/static/CACHE
find . -name '*.pyc' -delete
ERROR: You're running a virtualenv with Python 3.12.2.
We only support >= 3.11.6, < 3.12.
Either run "rm -rf .venv && direnv allow" to
OR set SENTRY_PYTHON_VERSION=3.12.2 to an .env file to bypass this check."
make: *** [ensure-venv] Error 1
Traceback (most recent call last):
File "/Users/asottile/workspace/./sentry/.venv/bin/devenv", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/asottile/workspace/sentry/.venv/lib/python3.11/site-packages/devenv/main.py", line 154, in main …
```

ensure `devenv sync` has run in getsentry before bootstrapping

---

.github/workflows/bootstrap.yml
devenv/bootstrap.py

depends on https://github.com/getsentry/sentry/pull/67624

ref: no more rmrf sentry config

---

README.md

doc: refresh README

---

ci/devenv-bootstrap.sh
devenv/fetch.py

https://github.com/getsentry/sentry/pull/72870#discussion_r1643236206

feat: fetch runs post_fetch if available

---

devenv/lib/fs.py

Spawn a new shell process to get the value of $ZDOTDIR, if set. This is needed so Homebrew will install correctly for users who have moved their zsh config directory. Note that we cannot simply read this from the environment, as one of the common methods of setting this value (via ~/.zshenv), results in it being a shell variable and not entering the environment.

fix: Use correct .zshrc location when $ZDOTDIR set

---

README.md

About time I added some comprehensive minimal examples on how to actually do things. Also revised some stuff.
best viewed: https://github.com/getsentry/devenv/blob/ae74a77150ab84566aec2ab921c7b5f6f088b94f/README.md

doc: add a lot of useful examples

---

devenv/lib/fs.py
devenv/lib/gcloud.py
devenv/lib/node.py
devenv/lib/tenv.py
devenv/lib/volta.py
tests/lib/test_fs.py

f/u to https://github.com/getsentry/devenv/pull/142
properly quotes everything in shims and removes unnecessary /usr/bin/env!

quote all the shims and remove unncessary /usr/bin/env

---

pyproject.toml

partial revert of https://github.com/getsentry/devenv/pull/151

fix: restore py310 metadata

---

.github/workflows/bootstrap.yml
ci/devenv-bootstrap.sh
devenv/lib/colima.py
devenv/lib/limactl.py

used here: https://github.com/getsentry/sentry/pull/78800
closes https://github.com/getsentry/devenv/issues/146 after this is used to upgrade limactl in sentry

feat: repo-local limactl

---

ci/devenv-bootstrap.sh

fix(ci): use homebrew lima

---

ci/devenv-bootstrap.sh

i recently upgraded nodejs in sentry and that's resulting in ci fails here
thought i fixed this problem before but guess not - should be correct this time

fix(ci): actually override devenv config and resync

---

devenv/lib/docker.py

forgot to check this in, sorry
will be releasing 1.14.1

fix: docker version detection

---

README.md
devenv/constants.py
devenv/main.py
devenv/sync.py

https://getsentry.atlassian.net/issues/DEVINFRA-486
this adds links to the troubleshooting docs in help text and also when `sync` fails

feat: troubleshooting docs

---

devenv/lib/colima.py
devenv/lib/limactl.py

colima 0.8.1 fixes https://github.com/abiosoft/colima/issues/1029 which people have been running into

feat: upgrade to colima 0.8.1 and limactl 1.0.3

---

devenv/checks/credsStore.py
devenv/checks/dockerDesktop.py
devenv/checks/limaDns.py
devenv/doctor.py
tests/doctor/test_run_checks.py

https://linear.app/getsentry/issue/DI-477/devenv-doctor-should-detect-if-docker-desktop-is-running-and-recommend

feat(doctor): stop docker desktop if it's running

---

README.md
devenv/lib/uv.py

feat: install uv
